# Generated by Django 3.1.7 on 2021-02-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='is_free_video',
            field=models.BooleanField(default=False),
        ),
    ]
