# Generated by Django 3.1.7 on 2021-02-25 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_remove_videos_can_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoscategory',
            old_name='slug_Field',
            new_name='slug',
        ),
    ]
