# Generated by Django 3.1.7 on 2021-03-04 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20210303_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-video_added'], 'verbose_name_plural': 'Videos'},
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_URL',
        ),
        migrations.AddField(
            model_name='video',
            name='video_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
