# Generated by Django 3.1.7 on 2021-03-04 09:21

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20210304_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_URL',
            field=embed_video.fields.EmbedVideoField(default='www.yoututbe.com'),
            preserve_default=False,
        ),
    ]
