vscode:
  extensions:
    - batisteo.vscode-django@1.3.0:BebJLpCGbZYwexWZ2LakeQ==
    - samuelcolvin.jinjahtml@0.16.0:BVmmMq9AdPxbGoooHnjjUg==
    - ecmel.vscode-html-css@1.9.1:IxAxIfaC6OW70vfl5VyKbg==